; hotkeys
global startRotationHotkey
global customChatCommandHotkey
; toggles
global start_rotation_toggle
; activators
global start_rotation_active
global custom_chat_command_active
global key1_active
global key2_active
global key3_active
global key4_active
global key5_active
global key6_active
global key7_active
global key8_active
global key9_active
global key10_active
global key11_active
global key12_active
global key1_cast_active
global key2_cast_active
global key3_cast_active
global key4_cast_active
global key5_cast_active
global key6_cast_active
global key7_cast_active
global key8_cast_active
global key9_cast_active
global key10_cast_active
global key11_cast_active
global key12_cast_active
; keylists
global rotation_key_set
global key1
global key2
global key3
global key4
global key5
global key6
global key7
global key8
global key9
global key10
global key11
global key12
; colors
global ready_key_color
global cd_key_color
global key1_color
global key2_color
global key3_color
global key4_color
global key5_color
global key6_color
global key7_color
global key8_color
global key9_color
global key10_color
global key11_color
global key12_color
; delays
global skills_delay
global key1_cast_delay
global key2_cast_delay
global key3_cast_delay
global key4_cast_delay
global key5_cast_delay
global key6_cast_delay
global key7_cast_delay
global key8_cast_delay
global key9_cast_delay
global key10_cast_delay
global key11_cast_delay
global key12_cast_delay
;states
global key1_accept_click
global key2_accept_click
global key3_accept_click
global key4_accept_click
global key5_accept_click
global key6_accept_click
global key7_accept_click
global key8_accept_click
global key9_accept_click
global key10_accept_click
global key11_accept_click
global key12_accept_click
global key1_click_times
global key2_click_times
global key3_click_times
global key4_click_times
global key5_click_times
global key6_click_times
global key7_click_times
global key8_click_times
global key9_click_times
global key10_click_times
global key11_click_times
global key12_click_times
; coords
global key1_color_X
global key1_color_Y
global key2_color_X
global key2_color_Y
global key3_color_X
global key3_color_Y
global key4_color_X
global key4_color_Y
global key5_color_X
global key5_color_Y
global key6_color_X
global key6_color_Y
global key7_color_X
global key7_color_Y
global key8_color_X
global key8_color_Y
global key9_color_X
global key9_color_Y
global key10_color_X
global key10_color_Y
global key11_color_X
global key11_color_Y
global key12_color_X
global key12_color_Y
global display_rotation_X
global display_rotation_Y
; commands
global chat_command
